// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pl.edu.agh.toik.twittercrawler.model;

import org.springframework.beans.factory.annotation.Configurable;
import pl.edu.agh.toik.twittercrawler.model.Stats;

privileged aspect Stats_Roo_Configurable {
    
    declare @type: Stats: @Configurable;
    
}
