// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pl.edu.agh.toik.twittercrawler.web;

import org.springframework.beans.factory.annotation.Configurable;
import pl.edu.agh.toik.twittercrawler.web.ApplicationBean;

privileged aspect ApplicationBean_Roo_Configurable {
    
    declare @type: ApplicationBean: @Configurable;
    
}
