// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pl.edu.agh.toik.twittercrawler.web;

import java.io.Serializable;
import pl.edu.agh.toik.twittercrawler.web.EntryBean;

privileged aspect EntryBean_Roo_Serializable {
    
    declare parents: EntryBean implements Serializable;
    
    private static final long EntryBean.serialVersionUID = 1L;
    
}
